/*Muhammad Saqib,Zia Ur Rehman,Rizwan Iqbal.
Project: Make an IDE for C Language*/
#include<process.h>
#include<string.h>
#include<stdio.h>
#include<conio.h>
#include<dos.h>
#include<iostream.h>
#include<graphics.h>

#include"msg.h"
#include"menu1.h"
#include"menu2.h"
#include"menu_sea.h"
#include"menu_run.h"
#include"menu_com.h"
#include"project1.h"
#include"graph_me.h"
void main()
{       graph();
       project1();

}
